### PR TITLE
Add link to blogpost about building a slack clone

### PR DESCRIPTION
**Pull request by tonysm**
The blogpost doesn't cover _how_ I built the homepage clone, though. Does it still fit? The demo uses it though, and the code is posted in the [TailwindComponents page](https://tailwindcomponents.com/component/slackish-homepage)

### CODE REVIEW

**Comment by joshmanders** [comment]
I did a quick scan of the article and there doesn't really seem to be much that is tailwind related, more Vue and Laravel. I'd prefer to keep stuff more focused on Tailwind than just as an aside.

**Comment by joshmanders** [comment]
@m1guelpf What do you think, my man?

**Comment by m1guelpf** [comment]
@joshmanders On one hand, you're right and the blog post is more about the application than about designing & Tailwind. On the other hand, I asked @tonysm to PR this via twitter, so I feel bad rejecting this.

**Comment by tonysm** [comment]
No hurt feelings. I'll close it, haha.

**Comment by joshmanders** [comment]
Sorry @tonysm. I feel bad too. But anything that focuses primarily on Tailwind, go ahead and PR it. I'll merge it if Miguel doesn't get there before me :)

**Pull request closed without merging**
